sudo: false
language: php
php:
  - nightly
  - 5.6
  - 5.5
  - 5.4
  - hhvm

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - bower_components
    - node_modules

install:
  - npm install -g npm@latest
  - npm install -g bower gulp jscs
  - npm install
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require squizlabs/php_codesniffer
  - composer global require phpmd/phpmd
  - composer install -o

script:
  - npm run build
  - npm run jshint
  - npm run jscs
  - phpcs --standard=ruleset.xml --extensions=php --ignore=node_modules,bower_components,vendor -n -s .
  - phpmd app text cleancode,codesize,controversial,design,naming,unusedcode
