sudo: false
language: php
cache:
  directories:
  - node_modules
php:
- '5.6'
- '5.5'
- '5.4'

before_install:
  - npm cache clean
  - npm prune
  - npm install -g bower gulp jscs
  - npm update
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - npm run build
  - npm run jshint
  - npm run jscs
  - phpcs --standard=ruleset.xml --extensions=php -n -s .
